---
collections:
  - name: amazon.aws
    version: 3.0.0
  - name: redhat.rhel_system_roles
    version: 1.7.3
  - name: ansible.controller 
    version: 4.1.1
  - name: containers.podman 
    version: 1.9.3
  - name: community.general
    version: 4.7.0
  