- name: Deploy demo Node JS backend
  hosts: all  
  vars:
    git_repo_url: https://github.com/corumj/node-js-postgresql-crud-example
    repo_path: /home/ec2-user/demoapp 
    repo_branch: master

  tasks:
    - name: Clone the app repository 
      git: 
        repo: "{{ git_repo_url }}"
        dest: "{{ repo_path }}"
        version: "{{ repo_branch }}"

    - name: Install packages based on package.json
      npm:
        path: "{{ repo_path }}"
        state: present

    - name: debug this variable 
      debug:
        var: "{{ hostvars[groups['tag_app_database']] }}"

    - name: update db.config.js with db connection info 
      lineinfile:
        path: "{{ repo_path }}/app/config/db.config.js"
        regexp: '  HOST: "localhost",'
        line: "  HOST: {{ hostvars[groups['tag_app_database'][1]]['private_ip_address'] }},"

    - name: update db.config.js with db secret info 
      lineinfile:
        path: "{{ repo_path }}/app/config/db.config.js"
        regexp: '  USER: "postgres",'
        line: "  USER: {{ ansible_password }},"


    - name: copy demoapp.service to server
      become: yes
      copy:
        src: files/demoapp.service
        dest: /etc/systemd/system/demoapp.service

    - name: enable and start demoapp service
      become: yes
      systemd:
        name: demoapp
        daemon_reload: yes 
        enabled: yes 
        state: started

    - name: enable and start service
      systemd:
        name: dcmetromap
        daemon_reload: yes
        enabled: yes
        state: started

    - name: Provide URL to test backend
      debug:
        msg: "http://{{ ansible_host }}/"