---
- name: Gather facts for fact storage
  hosts: all 
  tasks:
    - name: Setup Module
      setup:
      register: linux_facts 
      when: ansible_os_family == "RedHat"

    # - name: Gather Junos Facts 
    #   junipernetworks.junos.junos_facts:
    #   register: junos_facts 

    - name: Print facts 
      debug: 
        var: linux_facts 

    
