- name: Setup PostgreSQL 
  hosts: all
  vars:
    postgresql_databases:
      - name: testdb
    postgresql_users:
      - name: example_user
        password: example_pass
    postgresql_service_state: started
    postgresql_service_enabled: true
    postgresql_hba_entries:
      - { type: host, database: all, user: all, address: '10.0.0.0/16', auth_method: md5 }
  become: yes
  
  roles:
    - geerlingguy.postgresql