- name: Setup PostgreSQL 
  hosts: tag_postgres
  vars:
    postgresql_databases:
      - name: testdb
    postgresql_users:
      - name: postgres
        password: "{{ ansible_password }}"
  become: yes
  
  roles:
    - geerlingguy.postgresql