---
- name: Use TimeSync RHEL System Role 
  hosts: all 
  become: yes
  collections:
    - community.general
  vars:
    timesync_ntp_servers:
      - hostname: 2.rhel.pool.ntp.org
        pool: yes 
        iburst: yes 
    timesync_ntp_provider: chrony
  roles:
    - role: redhat.rhel_system_roles.timesync